### ISSUE TITLE
Problem with Epson ET-2550

### ISSUE THREAD

**Issue by ash123-germany** [SeydX/homebridge-printer#10]
Firts i got Error 426:

25.2.2021, 23:24:05 [PrinterPlatform] Error: Received unexpected response status 426 from the printer.
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/@sealsystems/ipp/lib/request.js:85:12)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

After a while it changed to:
25.2.2021, 23:38:56 [PrinterPlatform] Error: Received unexpected response status 404 from the printer.
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/@sealsystems/ipp/lib/request.js:85:12)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

in Apple Home see only the switch and Contactsnsor , when i print no changes !

my config fiele:

[
    {
        "name": "Epson ET-2550",
        "address": "http://192.168.178.41:631/ipp/printer",
        "polling": 10,
        "manufacturer": "Epson",
        "model": "ET-2550",
        "serialNumber": "12345"
    }
]

try as well with ipp instead of http and with lower and larger polling time  No changes

mabe it is important i use Hoobs 

HOOBS 3 Version | 3.3.2
-- | --
Node Version | 14.15.1

**Comment by SeydX** [comment]
@ash123-germany 

It seems there is an protocol error

Can you try following config pls

[
{
"name": "Epson ET-2550",
"address": "ipp://192.168.178.41:631/ipp/printer",
"polling": 10,
"manufacturer": "Epson",
"model": "ET-2550",
"serialNumber": "12345"
}
]

**Comment by ash123-germany** [comment]
Hi SeydX,
thanks for the fast Responce , i try this as well after reading some other comments here . And i did it today too , same responce:

27.2.2021, 19:49:35 [PrinterPlatform] Epson ET-2550: An error occured during getting state
27.2.2021, 19:49:35 [PrinterPlatform] Error: Received unexpected response status 404 from the printer.
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/@sealsystems/ipp/lib/request.js:85:12)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

Config:
[
    {
        "name": "Epson ET-2550",
        "address": "ipp://192.168.178.41:631/ipp/printer",
        "polling": 10,
        "manufacturer": "Epson",
        "model": "ET-2550",
        "serialNumber": "12345"
    }
]

**Comment by ash123-germany** [comment]
After update same:
27.2.2021, 19:57:06 [PrinterPlatform] Epson ET-2550: An error occured during getting state
27.2.2021, 19:57:06 [PrinterPlatform] Error: Received unexpected response status 404 from the printer.
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/@sealsystems/ipp/lib/request.js:85:12)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

as well with http

**Comment by ash123-germany** [comment]
wrong buttom

**Comment by SeydX** [comment]
@ash123-germany 

are u sure that the given ipp printer of your printer is correct? 

404 means not found

**Comment by ash123-germany** [comment]
Hi , yes im sure 

 


out of Fritz Box:

 

 

BR
Arnd


 
 

Gesendet: Samstag, 27. Februar 2021 um 20:01 Uhr
Von: "Seyd" <notifications@github.com>
An: "SeydX/homebridge-printer" <homebridge-printer@noreply.github.com>
Cc: "ash123-germany" <ash123@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [SeydX/homebridge-printer] Problem with Epson ET-2550 (#10)


 

@ash123-germany

are u sure that the given address printer of your printer is correct?

404 means not found

**Comment by SeydX** [comment]
@ash123-germany 

You need the address to the ipp endpoint

read this

https://github.com/SeydX/homebridge-printer/issues/1

**Comment by ash123-germany** [comment]
Wheen i type in chrome or Edge http://192.168.178.41:631/   i get a side calling : http://192.168.178.41:631/PRESENTATION/HTML/TOP/INDEX.HTML

when i tery to use  http or ipp ://192.168.178.41:631//ipp/printer

i get error 404 

i look in config side from Printer : '        Erlaubt is marked

 IPP aktivieren
Nicht sichere Kommunikation erlauben :
 **Erlaubt** Nicht erlaubt
Kommunikationszeitüberschreitung (s) :
300
URL(Netzwerk) :
http://192.168.178.41:631/ipp/print
https://192.168.178.41:631/ipp/print

**Comment by ash123-germany** [comment]
ipp ://192.168.178.41:631/ipp/printer

How can i find out this adress on printer itself ?

**Comment by SeydX** [comment]
@ash123-germany 

read this issue 

https://github.com/SeydX/homebridge-printer/issues/1

i wrote a guide how to find the address

**Comment by ash123-germany** [comment]
Mhm its written in the config , this is funny

**Comment by ash123-germany** [comment]
when i cancel ipp/printer , 
i get this:
27.2.2021, 20:26:14 [PrinterPlatform] Epson ET-2550: {"version":"2.0","statusCode":"successful-ok","id":3240418,"operation-attributes-tag":{"attributes-charset":"utf-8","attributes-natural-language":"en-us"},"printer-attributes-tag":{"printer-is-accepting-jobs":true,"printer-make-and-model":"EPSON ET-2550 Series","printer-state":"idle","printer-up-time":568,"queued-job-count":0,"marker-names":["Black ink","Cyan ink","Magenta ink","Yellow ink"],"marker-levels":[99,100,100,100]}}

Do you expect something like this ?

**Comment by SeydX** [comment]
@ash123-germany 

yes thats the correct result

It should work now!

**Comment by ash123-germany** [comment]
27.2.2021, 20:34:42 [PrinterPlatform] Epson ET-2550: {"version":"2.0","statusCode":"successful-ok","id":89079657,"operation-attributes-tag":{"attributes-charset":"utf-8","attributes-natural-language":"en-us"},"printer-attributes-tag":{"printer-is-accepting-jobs":false,"printer-make-and-model":"EPSON ET-2550 Series","*_*printer-state":"processing**_","printer-up-time":1067,"queued-job-count":1,"marker-names":["Black ink","Cyan ink","Magenta ink","Yellow ink"],"marker-levels":[99,100,100,100]}}
And it reconised Printer state ! an in HOME i see a swich   and a kontaktsender which is open when Printer is printing !

GREAT work

P.S.:   can you make the Switch working   ?  Printer on/off   ?

**Comment by ash123-germany** [comment]
Mean i see once in Log , when i switch off the Printer:

27.2.2021, 20:38:14 [PrinterPlatform] Error: Received unexpected response status 500 from the printer.
    at ClientRequest.<anonymous> (/home/hoobs/.hoobs/node_modules/@sealsystems/ipp/lib/request.js:85:12)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

And then 27.2.2021, 20:38:43 [PrinterPlatform] Epson ET-2550: Can not reach printer!

But in Home the switch is still on ON

**Comment by SeydX** [comment]
Yep its already mentioned here

https://github.com/SeydX/homebridge-printer/issues/11

will fix it in the next version, closing this issue now

**Comment by ash123-germany** [comment]
oK GREAT work , thanks  a lot.

One Idea at the end . i menan in real live im a tester from new products in mobile sector.

the Polling request you need are written in the normal log protocol.
I think it would be better to seperate them in a special log . 
while to analyse other errors is hard to do while you have so many polling requests.

Thsi is only an idea , i do notz know if it is possible here .
And its not a criticism, you did a great usefull work.
 Br
Arnd

**Comment by SeydX** [comment]
@ash123-germany 

thanks, i ll put this in my todo list :)
