### ISSUE TITLE
Error: Received unexpected response status 426 from the printer

### ISSUE THREAD

**Issue by JayJay-Master** [SeydX/homebridge-printer#15]
Hi SeydX,

I installed a new Epson ET-2756 printer in homebridge-print and got following error-message:

[4/9/2021, 3:41:29 PM] [PrinterPlatform] Epson ET-2756 Sensor: An error occured during adding filter services
[4/9/2021, 3:41:29 PM] [PrinterPlatform] Error: Received unexpected response status 426 from the printer.
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-printer/node_modules/@sealsystems/ipp/lib/request.js:85:12)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)

Corresponding config enrty is:

                {
                    "name": "Epson ET-2756",
                    "address": "http://epson-et-2756:631/ipp/print",
                    "polling": 30,
                    "marker": true,
                    "manufacturer": "Epson",
                    "model": "Eco Tank ET-2756",
                    "serialNumber": "123"
                }

If I use IP number instead of DNS name I got the same. With marker = false I gott also this error, but without details error message first time after restarting hombridge.

Maybe helpful additional information from Discovery app on my iPhone:
mopria-certified = 1.3
rp = ipp/print
TLS = 1.2
txtvers = 1
ty = EPSON ET-2750 Series

Thanks in advance.

**Comment by JayJay-Master** [comment]
Hi, 
any idea or newa for this issue?

**Comment by ash123-germany** [comment]
1. Start the web page of the Printer  http://epson-et-2756   do not take care about the security hint . Epson uses private keys

2. on the webpage login as administrator : Password is Allways the serialnumber of your printer.

3. On top of page select "advanced Settings"

4.  on left side select : "services " Protocol"

There you should find " IPP settings"    Activate them if not allready done and "ALLOW" them .

SAVE
 And then restart again 
 
 After a while the ERROR 426 will be disapeer .   
 
 It works now on My Epson ET 2550 and ET2821

**Comment by JayJay-Master** [comment]
Thanks a lot. That solves the issue by me too.
